spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:/Users/Vetom/OneDrive/Dokumenty/GitHub/udemy-kurs-spring/test'
  jpa:
    hibernate:
      ddl-auto: validate

